version: "3.4"


services:
  augmego-redis:
    container_name: augmego-redis
    image: redis:latest
    ports:
      - "6379:6379"
    
  # augmego-memcached:
  #   container_name: augmego-memcached
  #   image: memcached:latest
  #   ports:
  #     - "11211:11211"

  augmego-postgres:
    container_name: augmego-postgres
    environment:
      POSTGRES_DB: augmego-postgres
      POSTGRES_USER: augmego-postgres
      POSTGRES_PASSWORD: changeme
    image: postgres:15
    expose:
      - "5432"

  augmego-django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      REDIS_HOST: augmego-redis
      MEMCACHED_HOST: augmego-memcached
      PAYPAL_BUSINESS_LIVE: "${PAYPAL_BUSINESS_LIVE}"
      PAYPAL_BUSINESS_TEST: "${PAYPAL_BUSINESS_TEST}"
      PAYPAL_TEST: "${PAYPAL_TEST}"
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  augmego-celery:
    build: .
    command: celery -A quickstartproject worker --loglevel=info
    environment:
      REDIS_HOST: augmego-redis
    volumes:
      - .:/usr/src/app
    depends_on:
      - augmego-django
      - augmego-redis

  augmego-celerybeat:
    build: .
    command: celery -A quickstartproject beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      REDIS_HOST: augmego-redis
    volumes:
      - .:/usr/src/app
    depends_on:
      - augmego-django
      - augmego-redis

  augmego-nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - augmego-django

  augmego-ngrok:
    container_name: augmego-ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/ngrok.yaml"
    volumes:
      - ./ngrok.yaml:/ngrok.yaml
    ports:
        - 4040:4040
    