version: "3.4"


services:
  augmego-redis:
    container_name: augmego-redis
    image: redis:latest
    ports:
      - "6379:6379"
    
  augmego-memcached:
    container_name: augmego-memcached
    image: memcached:latest
    ports:
      - "11211:11211"

  augmego-postgres:
    container_name: augmego-postgres
    environment:
      POSTGRES_DB: augmego-postgres
      POSTGRES_USER: augmego-postgres
      POSTGRES_PASSWORD: changeme
    image: postgres:15
    expose:
      - "5432"

  augmego-django: &AUGMEGO-DJANGO
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      REDIS_HOST: augmego-redis
      MEMCACHED_HOST: augmego-memcached
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  augmego-django-ai:
    # Copy keys from augmego-django (above)
    << : *AUGMEGO-DJANGO
    container_name: augmego-django-ai
    ports:
      - "3000:3000"
    command: sh loopit.sh python3 manage.py create_ai
    depends_on:
      - augmego-django
      - augmego-ngrok

  # augmego-celery-worker:
  #   build: .
  #   command: celery -A quickstartproject worker -l INFO
  #   environment:
  #     REDIS_HOST: augmego-redis
  #     MEMCACHED_HOST: augmego-memcached
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - augmego-redis
  #     - augmego-postgres

  augmego-nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - augmego-django

  augmego-ngrok:
    container_name: augmego-ngrok
    image: wernight/ngrok
    environment:
      NGROK_PORT: "8000"
      NGROK_DEBUG: "true"
      NGROK_AUTH: "1m9OJapnAWad5yE5CxK8Woo9gkU_62VCktHhMGu3D1ycmM2aH"
      NGROK_HOSTNAME: "augmego.ngrok.app"
      NGROK_LOOK_DOMAIN: "kubernetes.docker.internal"
    depends_on:
      - augmego-django

  augmego-ngrok-ai:
    container_name: augmego-ngrok-ai
    image: wernight/ngrok
    environment:
      NGROK_PORT: "3000"
      NGROK_DEBUG: "true"
      NGROK_AUTH: "1m9OJapnAWad5yE5CxK8Woo9gkU_62VCktHhMGu3D1ycmM2aH"
      NGROK_HOSTNAME: "augmego.ngrok.io"
      NGROK_LOOK_DOMAIN: "kubernetes.docker.internal"
    depends_on:
      - augmego-django-ai
    