# Generated by Django 4.2.7 on 2023-11-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Web Page', max_length=100)),
                ('image', models.ImageField(upload_to='media/texture-image/')),
            ],
        ),
    ]
