# Generated by Django 5.0 on 2023-12-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texture', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='name',
            field=models.CharField(default='My Web Page', max_length=100, unique=True),
        ),
    ]
