# Generated by Django 5.0.6 on 2024-05-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texture', '0002_alter_texture_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextureAtlas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/texture-atlas/')),
            ],
        ),
    ]
