# Generated by Django 5.0.6 on 2024-05-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texture', '0003_textureatlas'),
    ]

    operations = [
        migrations.AddField(
            model_name='textureatlas',
            name='data_json',
            field=models.JSONField(default=[]),
        ),
    ]
