# Generated by Django 5.0.6 on 2024-07-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_family_password_familyconnection_is_owner'),
        ('texture', '0004_textureatlas_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='texture',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.family'),
        ),
        migrations.AddField(
            model_name='textureatlas',
            name='family',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.family'),
        ),
    ]
