# Generated by Django 5.0.6 on 2024-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texture', '0005_texture_family_textureatlas_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='name',
            field=models.CharField(default='My Web Page', max_length=100),
        ),
    ]
