# Generated by Django 5.0.6 on 2024-06-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Tutorial', max_length=100)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media/tutorial-image/')),
            ],
        ),
    ]
