# Generated by Django 5.0.6 on 2024-08-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='order_id',
            field=models.FloatField(default=0.0),
        ),
    ]
