# Generated by Django 4.2.7 on 2023-11-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('texture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.BigIntegerField()),
                ('y', models.BigIntegerField()),
                ('z', models.BigIntegerField()),
                ('texture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='texture.texture')),
            ],
        ),
    ]
