# Generated by Django 5.0.1 on 2024-03-02 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0001_initial'),
        ('person', '0002_person_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.BigIntegerField()),
                ('y', models.BigIntegerField(default=0)),
                ('z', models.BigIntegerField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
            ],
        ),
    ]
