# Generated by Django 5.0.6 on 2024-05-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0002_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='x2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='y2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chunk',
            name='z2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='x',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chunk',
            name='z',
            field=models.BigIntegerField(default=0),
        ),
    ]
