# Generated by Django 5.0.6 on 2024-07-16 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cube', '0003_chunk_x2_chunk_y2_chunk_z2_alter_chunk_x_and_more'),
        ('person', '0009_family_password_familyconnection_is_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='cube',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.family'),
        ),
    ]
