# Generated by Django 5.0.4 on 2024-04-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_remove_userlogin_hashed_ip_userlogin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='session_end',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
