# Generated by Django 5.0.1 on 2024-02-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
