# Generated by Django 5.0.1 on 2024-03-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='points',
            field=models.BigIntegerField(default=0),
        ),
    ]
