# Generated by Django 5.0.3 on 2024-03-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_person_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='points',
        ),
        migrations.AddField(
            model_name='person',
            name='amica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
