# Generated by Django 5.0.3 on 2024-03-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_remove_person_points_person_amica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='amica',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
