# Generated by Django 5.0.6 on 2024-05-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_amica'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
