# Generated by Django 5.0.6 on 2024-06-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
