# Generated by Django 5.0.6 on 2024-07-22 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_family_password_familyconnection_is_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='avatar',
            new_name='avatar_url',
        ),
    ]
