# Generated by Django 5.1.4 on 2024-12-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_person_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar_dance',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-dance/'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_idle',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-idle/'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_run',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-run/'),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_walk',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-walk/'),
        ),
    ]
