# Generated by Django 5.1.4 on 2024-12-06 21:03

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_person_avatar_dance_person_avatar_idle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar_walk',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-walk/', validators=[person.models.file_size_validator]),
        ),
    ]
