# Generated by Django 5.1.4 on 2024-12-06 21:07

import person.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_alter_person_avatar_walk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar/', validators=[person.models.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar_dance',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-dance/', validators=[person.models.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar_idle',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-idle/', validators=[person.models.file_size_validator]),
        ),
        migrations.AlterField(
            model_name='person',
            name='avatar_run',
            field=models.FileField(blank=True, null=True, upload_to='media/person-avatar-run/', validators=[person.models.file_size_validator]),
        ),
    ]
