# Generated by Django 4.2.6 on 2023-10-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='html',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.TextField(blank=True),
        ),
    ]
