# Generated by Django 4.2.6 on 2023-10-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_webpage_html_alter_webpage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='name',
            field=models.CharField(default='My Web Page', max_length=100),
        ),
    ]
