# Generated by Django 4.2.7 on 2023-11-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_webpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='image',
            field=models.ImageField(blank=True, height_field=256, null=True, upload_to='media/%Y/%m/%d/', width_field=256),
        ),
    ]
