# Generated by Django 4.2.7 on 2023-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_alter_webpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
